# Generated by Django 5.1.4 on 2024-12-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('short_description', models.CharField(max_length=255, verbose_name='Descrição curta')),
                ('long_description', models.TextField(verbose_name='Descrição longa')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Imagem')),
                ('slug', models.SlugField(unique=True)),
                ('marketing_price', models.FloatField(verbose_name='Preço de marketing')),
                ('promotional_marketing_price', models.FloatField(default=0, verbose_name='Preço de marketing promocional')),
                ('product_type', models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1, verbose_name='Tipo do produto')),
            ],
        ),
    ]
